# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - hikeplanner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9B1727EB33914409A716709016C5A404 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_F3EAD218318D420D976C378D8CA5E784 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9B1727EB33914409A716709016C5A404 }}/haonannu/mdm-hikeplanner:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6BC924EFBC2A47BC9566A3ADB0652898 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EA5B7031F9DE436F82BBBD191C289B56 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_AB67A222EDE5440C91C82BB028EEB1D4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'hikeplanner'
          slot-name: 'Production'
          images: 'ghcr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9B1727EB33914409A716709016C5A404 }}/haonannu/mdm-hikeplanner:${{ github.sha }}'
          